version: '3.9'
services:
  dbft_api:
    build: ${APICLIBUILDDIR}#${APIBRANCH}:API
    # build: ../../../OGrEE-API
    image: dbft/api:dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_api
    entrypoint: /home/main
    environment:
      - api_port=3551
      - db_host=${COMPOSE_PROJECT_NAME}_db
      - db_port=27017
      - db_user=$TENANT
      - db_pass=$PASSWORD
      - db=$TENANT
      - token_password=yourSecretPasswordGoesHere
    ports:
      - ${APIPORT}:3551
    depends_on:
      - dbft_db
    restart: on-failure:10

    #Specifying the environment variables here is the superior option compared to inserting
    #the .env file and building an image. Here you can specify all the parameters of the
    #the API 

  dbft_db:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
        - DB_NAME=$TENANT
        - CUSTOMER_API_PASS=$PASSWORD
        - CUSTOMER_RECORDS_DB=ogree

        - ADMIN_DB=admin
        - SUPER_USER=super
        - SUPER_PASS=superpassword

        - ADMIN_USER=admin
        - ADMIN_PASS=adminpassword

        - GUARD_USER=guard
        - GUARD_PASS=adminpassword
    volumes:
        -  ${MONGOINIT}/init.sh:/docker-entrypoint-initdb.d/init.sh
        -  ${MONGOINIT}/dbft.js:/home/dbft.js
        -  ${MONGOINIT}/addCustomer.sh:/home/addCustomer.sh
        -  ${MONGOINIT}/addCustomer.js:/home/addCustomer.js
    #By default MongoDB will attempt to take port 27017, so just map it
    #for ease of use


  # Deploying the CLI in an orchestrated fashion does 
  # not work since containers exit when a program
  # is done executing. Instead make container 'hang'
  # to allow for on demand access. 
  # The 'tty: true' entry allows the container to hang 
  # by using the container's shell
  # The cli binary is found @ /home/cli
  dbft_cli:
   build: ${APICLIBUILDDIR}#${CLIBRANCH}:CLI
  #  build: ${LOCAL_CLI_BUILD_DIR}
   image: dbft/cli:dockerfile
   profiles: ["cli"]
   container_name: ${COMPOSE_PROJECT_NAME}_cli
   tty: true
   environment:
     - acDrawableJson=null
     - apiKey=yourJWTKeyGoesHere
     - apiURL=http://localhost:3551
     - buildingDrawableJson=null
     - cabinetDrawableJson=null
     - corridorDrawableJson=null
     - deviceDrawableJson=null
     - drawLimit=1
     - drawable=all
     - groupDrawableJson=null
     - listenPort=5501
     - objTemplateDrawableJson=null
     - powerpanelDrawableJson=null
     - rackDrawableJson=null
     - roomDrawableJson=null
     - roomTemplateDrawableJson=null
     - rowDrawableJson=null
     - sensorDrawableJson=null
     - separatorDrawableJson=null
     - siteDrawableJson=null
     - tenantDrawableJson=./other/drawTemplates/tenant.json
     - tileDrawableJson=null
     - unityTimeout=10ms
     - unityURL=localhost:5500
     - updates=all
     - user=new@yo.com
   depends_on:
     - dbft_api

  dbft_webapp:
    build: 
      context: ${APPBUILDDIR}#${APPBRANCH}
      # context: ../../
      args:
      - API_URL=http://${APIEXTERNALURL}:${APIPORT}
    image: dbft/webapp:dockerfile
    profiles: ["web"]
    container_name: ${COMPOSE_PROJECT_NAME}_webapp
    ports:
      - ${WEBPORT}:80
    depends_on:
      - dbft_api
    restart: on-failure:10